// =============================================
// Showcase 种子数据 — 首次访问时写入本地库
// =============================================
// 数据形状对齐后端契约（frontend/src/lib/hooks.ts 的接口定义），
// 全部为演示用途的虚构数据。

import type { TableName } from "./db";

export const seedVersion = "2026-08-14-v1";

export const seeds: Record<TableName, unknown> = {
  jobs: [
    {
      id: 1,
      title: "高级前端工程师（React）",
      company: "星辰科技",
      location: "深圳 · 南山",
      url: "https://example.com/jobs/1",
      apply_url: "",
      source: "boss",
      summary: "负责核心业务前端架构与性能优化，参与组件库建设。",
      keywords: ["React", "TypeScript", "性能优化"],
      salary_min: 25,
      salary_max: 40,
      salary_text: "25-40K·16薪",
      education: "本科",
      experience: "3-5年",
      job_type: "全职",
      company_size: "500-1000人",
      company_industry: "互联网",
      company_logo: "",
      is_campus: false,
      triage_status: "inbox",
      pool_id: null,
      posted_at: "2026-08-10T10:00:00",
      created_at: "2026-08-10T10:00:00",
    },
    {
      id: 2,
      title: "后端开发工程师（Golang）",
      company: "云帆数据",
      location: "上海 · 张江",
      url: "https://example.com/jobs/2",
      apply_url: "",
      source: "zhilian",
      summary: "负责数据平台后端服务设计与开发，高并发实时链路。",
      keywords: ["Golang", "Kafka", "微服务"],
      salary_min: 28,
      salary_max: 45,
      salary_text: "28-45K·15薪",
      education: "本科",
      experience: "3-5年",
      job_type: "全职",
      company_size: "100-500人",
      company_industry: "大数据",
      company_logo: "",
      is_campus: false,
      triage_status: "inbox",
      pool_id: null,
      posted_at: "2026-08-09T14:00:00",
      created_at: "2026-08-09T14:00:00",
    },
    {
      id: 3,
      title: "算法工程师（推荐系统）",
      company: "极光互动",
      location: "北京 · 望京",
      url: "https://example.com/jobs/3",
      apply_url: "",
      source: "neitui",
      summary: "负责推荐召回排序算法优化，探索大模型在推荐中的应用。",
      keywords: ["推荐系统", "PyTorch", "大模型"],
      salary_min: 35,
      salary_max: 55,
      salary_text: "35-55K·16薪",
      education: "硕士",
      experience: "1-3年",
      job_type: "全职",
      company_size: "1000人以上",
      company_industry: "游戏",
      company_logo: "",
      is_campus: false,
      triage_status: "picked",
      pool_id: 1,
      posted_at: "2026-08-08T09:00:00",
      created_at: "2026-08-08T09:00:00",
    },
    {
      id: 4,
      title: "产品经理（B 端）",
      company: "智联云服",
      location: "广州 · 天河",
      url: "https://example.com/jobs/4",
      apply_url: "",
      source: "zhilian",
      summary: "负责企业服务 SaaS 产品规划，推动数据化运营。",
      keywords: ["SaaS", "B端产品", "数据分析"],
      salary_min: 20,
      salary_max: 32,
      salary_text: "20-32K·14薪",
      education: "本科",
      experience: "3-5年",
      job_type: "全职",
      company_size: "500-1000人",
      company_industry: "企业服务",
      company_logo: "",
      is_campus: false,
      triage_status: "picked",
      pool_id: 2,
      posted_at: "2026-08-07T16:00:00",
      created_at: "2026-08-07T16:00:00",
    },
    {
      id: 5,
      title: "测试开发工程师",
      company: "星环安全",
      location: "成都 · 高新区",
      url: "https://example.com/jobs/5",
      apply_url: "",
      source: "boss",
      summary: "负责自动化测试平台建设与质量保障体系。",
      keywords: ["自动化测试", "Python", "CI/CD"],
      salary_min: 18,
      salary_max: 28,
      salary_text: "18-28K·13薪",
      education: "本科",
      experience: "1-3年",
      job_type: "全职",
      company_size: "100-500人",
      company_industry: "安全",
      company_logo: "",
      is_campus: false,
      triage_status: "ignored",
      pool_id: null,
      posted_at: "2026-08-06T11:00:00",
      created_at: "2026-08-06T11:00:00",
    },
    {
      id: 6,
      title: "前端开发实习生",
      company: "微光教育",
      location: "杭州 · 余杭",
      url: "https://example.com/jobs/6",
      apply_url: "",
      source: "shixiseng",
      summary: "参与在线教育产品前端开发，React + TypeScript。",
      keywords: ["React", "TypeScript", "实习生"],
      salary_min: 3,
      salary_max: 5,
      salary_text: "3-5K·日薪",
      education: "本科",
      experience: "应届",
      job_type: "实习",
      company_size: "100-500人",
      company_industry: "教育",
      company_logo: "",
      is_campus: true,
      triage_status: "inbox",
      pool_id: null,
      posted_at: "2026-08-05T10:00:00",
      created_at: "2026-08-05T10:00:00",
    },
    {
      id: 7,
      title: "AI 应用开发工程师",
      company: "灵枢智能",
      location: "深圳 · 福田",
      url: "https://example.com/jobs/7",
      apply_url: "",
      source: "neitui",
      summary: "基于大模型构建行业 AI 应用，负责 Agent 框架与推理链路。",
      keywords: ["大模型", "Agent", "RAG"],
      salary_min: 30,
      salary_max: 50,
      salary_text: "30-50K·15薪",
      education: "本科",
      experience: "1-3年",
      job_type: "全职",
      company_size: "50-100人",
      company_industry: "AI",
      company_logo: "",
      is_campus: false,
      triage_status: "inbox",
      pool_id: null,
      posted_at: "2026-08-04T09:30:00",
      created_at: "2026-08-04T09:30:00",
    },
    {
      id: 8,
      title: "数据分析师",
      company: "远见咨询",
      location: "远程",
      url: "https://example.com/jobs/8",
      apply_url: "",
      source: "liepin",
      summary: "为行业客户提供数据洞察与指标体系搭建服务。",
      keywords: ["SQL", "BI", "指标体系"],
      salary_min: 22,
      salary_max: 35,
      salary_text: "22-35K·14薪",
      education: "本科",
      experience: "3-5年",
      job_type: "全职",
      company_size: "50-100人",
      company_industry: "咨询",
      company_logo: "",
      is_campus: false,
      triage_status: "inbox",
      pool_id: null,
      posted_at: "2026-08-03T15:00:00",
      created_at: "2026-08-03T15:00:00",
    },
  ],
  pools: [
    { id: 1, name: "重点跟进", scope: "picked", description: "高意向岗位，优先推进", created_at: "2026-08-01T00:00:00" },
    { id: 2, name: "备选池", scope: "picked", description: "条件接近，可作备选", created_at: "2026-08-01T00:00:00" },
  ],
  profile: {
    id: 1,
    name: "林晓",
    title: "前端开发工程师",
    base_info_json: {
      name: "林晓",
      title: "前端开发工程师",
      phone: "138****0000",
      email: "linxiao@example.com",
      location: "深圳",
      summary: "3 年前端开发经验，专注 React 生态与前端工程化，对性能优化和用户体验有持续实践。",
    },
    sections: [
      {
        id: 101,
        section_type: "education",
        category_key: "education",
        title: "教育经历",
        sort_order: 0,
        visible: true,
        content_json: {
          school: "华南理工大学",
          degree: "本科",
          major: "软件工程",
          gpa: "3.7/4.0",
          startDate: "2019-09",
          endDate: "2023-06",
          description: "主修软件工程，参与校内开源项目与 ACM 集训队。",
        },
      },
      {
        id: 102,
        section_type: "workExperiences",
        category_key: "workExperiences",
        title: "工作经历",
        sort_order: 1,
        visible: true,
        content_json: {
          company: "云帆数据",
          position: "前端工程师",
          startDate: "2023-07",
          endDate: "至今",
          description: "负责数据平台前端架构；主导组件库建设，页面首屏耗时下降 40%。",
        },
      },
      {
        id: 103,
        section_type: "projects",
        category_key: "projects",
        title: "项目经历",
        sort_order: 2,
        visible: true,
        content_json: {
          name: "低代码搭建平台",
          role: "核心开发者",
          url: "",
          startDate: "2024-03",
          endDate: "2024-10",
          description: "面向运营人员的低代码页面搭建工具，服务 20+ 业务线。",
        },
      },
      {
        id: 104,
        section_type: "skills",
        category_key: "skills",
        title: "技能清单",
        sort_order: 3,
        visible: true,
        content_json: {
          items: ["React", "TypeScript", "Vite", "Node.js", "Webpack", "性能优化"],
        },
      },
    ],
  },
  resumes: [
    {
      id: 1,
      user_name: "林晓",
      title: "前端开发工程师-通用版",
      photo_url: "",
      template_id: null,
      is_primary: true,
      language: "zh",
      source_mode: "manual",
      source_job_ids: [],
      summary: "3 年前端开发经验，专注 React 生态与前端工程化。",
      contact_json: {
        name: "林晓",
        title: "前端开发工程师",
        email: "linxiao@example.com",
        phone: "138****0000",
        location: "深圳",
      },
      style_config: { primaryColor: "#2563eb", fontFamily: "Inter" },
      sections: [
        {
          id: 11,
          section_type: "experience",
          title: "工作经历",
          sort_order: 0,
          visible: true,
          content_json: [
            {
              company: "云帆数据",
              position: "前端工程师",
              startDate: "2023-07",
              endDate: "至今",
              description: "主导数据平台前端架构升级，组件库覆盖 12 个业务模块。",
            },
          ],
        },
        {
          id: 12,
          section_type: "internshipExperiences",
          title: "实习经历",
          sort_order: 1,
          visible: true,
          content_json: [
            {
              company: "微光教育",
              position: "前端实习生",
              startDate: "2022-06",
              endDate: "2022-12",
              description: "参与在线课堂产品开发，独立完成课件编辑器模块。",
            },
          ],
        },
        {
          id: 13,
          section_type: "education",
          title: "教育经历",
          sort_order: 2,
          visible: true,
          content_json: [
            {
              school: "华南理工大学",
              degree: "本科",
              major: "软件工程",
              startDate: "2019-09",
              endDate: "2023-06",
              description: "GPA 3.7/4.0，校 ACM 集训队成员。",
            },
          ],
        },
        {
          id: 14,
          section_type: "skill",
          title: "技能",
          sort_order: 3,
          visible: true,
          content_json: [{ category: "前端", items: ["React", "TypeScript", "Vite"] }],
        },
      ],
    },
    {
      id: 2,
      user_name: "林晓",
      title: "前端开发工程师-AI 方向",
      photo_url: "",
      template_id: null,
      is_primary: false,
      language: "zh",
      source_mode: "manual",
      source_job_ids: [7],
      summary: "前端工程化 + AI 应用开发经验，熟悉 Agent 与 RAG 链路。",
      contact_json: {
        name: "林晓",
        title: "前端开发工程师",
        email: "linxiao@example.com",
        phone: "138****0000",
        location: "深圳",
      },
      style_config: { primaryColor: "#7c3aed", fontFamily: "Inter" },
      sections: [
        {
          id: 21,
          section_type: "experience",
          title: "工作经历",
          sort_order: 0,
          visible: true,
          content_json: [
            {
              company: "云帆数据",
              position: "前端工程师",
              startDate: "2023-07",
              endDate: "至今",
              description: "负责 AI 助手前端接入，实现流式交互与工具调用可视化。",
            },
          ],
        },
        {
          id: 22,
          section_type: "projects",
          title: "项目经历",
          sort_order: 1,
          visible: true,
          content_json: [
            {
              name: "RAG 知识库问答",
              role: "全栈",
              startDate: "2025-01",
              endDate: "2025-04",
              description: "基于大模型的内部知识库问答系统，检索命中率 85%+。",
            },
          ],
        },
      ],
    },
  ],
  workspace: {
    tables: [
      {
        id: 1,
        name: "总表",
        is_total: true,
        record_count: 3,
        created_at: "2026-08-01T00:00:00",
        updated_at: "2026-08-12T00:00:00",
        schema: [
          { field_key: "company_name", label: "公司", type: "text", fixed: true, visible: true, width: 140, options: [], order: 0 },
          { field_key: "job_title", label: "岗位", type: "text", fixed: true, visible: true, width: 160, options: [], order: 1 },
          { field_key: "location", label: "地点", type: "text", fixed: true, visible: true, width: 110, options: [], order: 2 },
          { field_key: "current_stage", label: "当前阶段", type: "single_select", fixed: true, visible: true, width: 110, options: ["已投递", "笔试", "一面", "二面", "HR面", "Offer", "已拒绝"], order: 3 },
          { field_key: "next_action", label: "下一步", type: "text", fixed: false, visible: true, width: 150, options: [], order: 4 },
          { field_key: "next_action_at", label: "下一步时间", type: "datetime", fixed: false, visible: true, width: 150, options: [], order: 5 },
          { field_key: "updated_at", label: "更新时间", type: "datetime", fixed: true, visible: true, width: 140, options: [], order: 6 },
        ],
      },
      {
        id: 2,
        name: "实习投递",
        is_total: false,
        record_count: 1,
        created_at: "2026-08-02T00:00:00",
        updated_at: "2026-08-10T00:00:00",
        schema: [
          { field_key: "company_name", label: "公司", type: "text", fixed: true, visible: true, width: 140, options: [], order: 0 },
          { field_key: "job_title", label: "岗位", type: "text", fixed: true, visible: true, width: 160, options: [], order: 1 },
          { field_key: "current_stage", label: "当前阶段", type: "single_select", fixed: true, visible: true, width: 110, options: ["已投递", "笔试", "一面", "二面", "Offer", "已拒绝"], order: 2 },
          { field_key: "next_action", label: "下一步", type: "text", fixed: false, visible: true, width: 150, options: [], order: 3 },
          { field_key: "updated_at", label: "更新时间", type: "datetime", fixed: true, visible: true, width: 140, options: [], order: 4 },
        ],
      },
    ],
    current_table_id: 1,
    settings: {
      auto_row_height: true,
      auto_column_width: true,
      delete_subtable_sync_total_default: true,
      updated_at: "2026-08-12T00:00:00",
    },
    template_schema: [],
    stats: { total_records: 3, duplicate_records: 0 },
  },
  calendar_events: [
    { id: 1, title: "星辰科技 一面（视频）", event_type: "interview", start_time: "2026-08-16T14:00:00", end_time: "2026-08-16T15:00:00", description: "腾讯会议，链接见邮件", location: "线上", related_job_id: 1 },
    { id: 2, title: "云帆数据 在线笔试", event_type: "written_test", start_time: "2026-08-18T19:00:00", end_time: "2026-08-18T21:00:00", description: "牛客平台，时长 120 分钟", location: "线上", related_job_id: 2 },
    { id: 3, title: "灵枢智能 投递截止", event_type: "deadline", start_time: "2026-08-20T23:59:00", end_time: null, description: "内推截止", location: "", related_job_id: 7 },
    { id: 4, title: "极光互动 二面", event_type: "interview", start_time: "2026-08-22T10:30:00", end_time: "2026-08-22T11:30:00", description: "现场面试，带作品集", location: "北京 · 望京", related_job_id: 3 },
  ],
  progress_candidates: [
    {
      candidate_id: "demo_candidate_1",
      signal_id: "demo_signal_1",
      status: "pending",
      match_state: "unassigned",
      suggested_stage: "interview_1",
      channel: "email",
      sender: "hr@xingchen.example.com",
      received_at: "2026-08-13T09:00:00",
      subject: "面试邀请：高级前端工程师",
      body_sha256: "demo",
      snippet: "您好，感谢您投递星辰科技高级前端工程师岗位，我们邀请您参加第一轮技术面试……",
      rule_stage: "interview_1",
      classification_method: "deterministic_keyword",
    },
    {
      candidate_id: "demo_candidate_2",
      signal_id: "demo_signal_2",
      status: "pending",
      match_state: "suggested",
      suggested_stage: "written_test",
      channel: "email",
      sender: "noreply@yunfan.example.com",
      received_at: "2026-08-12T16:30:00",
      subject: "云帆数据 在线笔试通知",
      body_sha256: "demo",
      snippet: "您已通过简历筛选，请于 8 月 18 日晚参加在线笔试……",
      rule_stage: "written_test",
      classification_method: "deterministic_keyword",
      suggested_attempt_id: 1,
    },
    {
      candidate_id: "demo_candidate_3",
      signal_id: "demo_signal_3",
      status: "pending",
      match_state: "unassigned",
      suggested_stage: "rejected",
      channel: "email",
      sender: "jobs@yuanjian.example.com",
      received_at: "2026-08-11T10:00:00",
      subject: "关于您的申请",
      body_sha256: "demo",
      snippet: "感谢您的关注与投递，经过综合评估，本次暂不匹配……",
      rule_stage: "rejected",
      classification_method: "deterministic_keyword",
    },
  ],
  agent_runs: [],
  app_records: [
    {
      id: 1,
      table_id: 1,
      values: {
        company_name: "星辰科技",
        job_title: "高级前端工程师",
        location: "深圳",
        current_stage: "interview_1",
        next_action: "准备算法与项目深挖",
        next_action_at: "2026-08-15T12:00:00",
        updated_at: "2026-08-13T09:00:00",
      },
      is_duplicate: false,
    },
    {
      id: 2,
      table_id: 1,
      values: {
        company_name: "云帆数据",
        job_title: "后端开发工程师",
        location: "上海",
        current_stage: "written_test",
        next_action: "牛客刷题：贪心/动态规划",
        next_action_at: "2026-08-18T19:00:00",
        updated_at: "2026-08-13T10:00:00",
      },
      is_duplicate: false,
    },
    {
      id: 3,
      table_id: 1,
      values: {
        company_name: "极光互动",
        job_title: "算法工程师",
        location: "北京",
        current_stage: "interview_2",
        next_action: "复习推荐系统评估指标",
        next_action_at: "2026-08-22T10:30:00",
        updated_at: "2026-08-12T15:00:00",
      },
      is_duplicate: false,
    },
  ],
};
